---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxbackup-sa
  namespace: px-backup
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: pxbackup-sa
  namespace: px-backup
  annotations:
    kubernetes.io/service-account.name: pxbackup-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pxbackup-sa-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pxbackup-sa
  namespace: px-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin