import csv
import json
import logging
import os
import sys
import datetime  # Add datetime import
from typing import Any, Dict, List

import click
from rich.console import Console
from rich.table import Table


def setup_logging(log_file_path: str):
    """Configures logging to file and console."""
    log_dir = os.path.dirname(log_file_path)
    os.makedirs(log_dir, exist_ok=True)

    log_formatter_file = logging.Formatter(
        "%(asctime)s - %(levelname)s - [%(funcName)s] - %(message)s"
    )
    log_formatter_console = logging.Formatter("%(levelname)s: %(message)s")

    root_logger = logging.getLogger()
    # Clear existing handlers to avoid duplicate logs if re-running
    if root_logger.hasHandlers():
        root_logger.handlers.clear()
    root_logger.setLevel(logging.INFO)

    # File Handler (INFO level and above)
    file_handler = logging.FileHandler(log_file_path)
    file_handler.setFormatter(log_formatter_file)
    file_handler.setLevel(logging.INFO)
    root_logger.addHandler(file_handler)

    # Console Handler (WARNING level and above)
    console_handler = logging.StreamHandler(sys.stderr)  # Log warnings/errors to stderr
    console_handler.setFormatter(log_formatter_console)
    console_handler.setLevel(logging.WARNING)
    root_logger.addHandler(console_handler)


@click.command()
@click.option(
    "--input-csv",
    required=True,
    type=click.Path(exists=True, dir_okay=False, readable=True),
    help="Path to the input CSV file generated by k8s_rcrscountsize script.",
)
@click.option(
    "--num-groups",
    type=int,
    default=6,
    show_default=True,
    help="The desired number of balanced schedule groups.",
)
@click.option(
    "--weight-pvc",
    type=float,
    default=1048576.0,  # ~ GiB -> KiB
    show_default=True,
    help="Weight multiplier for TotalPVCCapacityGiB.",
)
@click.option(
    "--weight-core",
    type=float,
    default=1.0,
    show_default=True,
    help="Weight multiplier for TotalCoreResourcesSizeKiB.",
)
@click.option(
    "--weight-cr",
    type=float,
    default=1.0,
    show_default=True,
    help="Weight multiplier for TotalCustomResourceSizeKiB.",
)
@click.option(
    "--output-json",
    type=click.Path(dir_okay=False, writable=True),
    default="tmp/schedule_groups.json",
    show_default=True,
    help="Path for the detailed JSON output file.",
)
@click.option(
    "--output-summary",
    type=click.Path(dir_okay=False, writable=True),
    default="logs/schedule_summary.txt",
    show_default=True,
    help="Path for the summary text file.",
)
def main(
    input_csv: str,
    num_groups: int,
    weight_pvc: float,
    weight_core: float,
    weight_cr: float,
    output_json: str,
    output_summary: str,
):
    """Balances namespaces from an input CSV into a specified number of groups
    based on calculated weights derived from resource sizes, outputting a JSON
    file and a summary text file/console output.
    """
    # Generate timestamp
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    # --- Setup Logging with Timestamp ---
    log_dir = os.path.dirname("logs/schedule_balancer.log")
    log_filename = f"schedule_balancer_{timestamp}.log"
    log_file_path = os.path.join(log_dir, log_filename)
    setup_logging(log_file_path)  # Use timestamped log file path

    logging.info("Schedule balancer started.")
    logging.info(f"Input CSV: {input_csv}")
    logging.info(f"Number of groups: {num_groups}")
    logging.info(f"Weights: PVC={weight_pvc}, Core={weight_core}, CR={weight_cr}")
    logging.info(f"Output JSON path pattern: {output_json}")
    logging.info(f"Output Summary path pattern: {output_summary}")

    console = Console()

    # --- Construct Timestamped Output Paths ---
    output_json_dir, output_json_filename = os.path.split(output_json)
    output_json_name, output_json_ext = os.path.splitext(output_json_filename)
    timestamped_json_filename = f"{output_json_name}_{timestamp}{output_json_ext}"
    final_output_json_path = os.path.join(output_json_dir, timestamped_json_filename)

    output_summary_dir, output_summary_filename = os.path.split(output_summary)
    output_summary_name, output_summary_ext = os.path.splitext(output_summary_filename)
    timestamped_summary_filename = f"{output_summary_name}_{timestamp}{output_summary_ext}"
    final_output_summary_path = os.path.join(output_summary_dir, timestamped_summary_filename)

    logging.info(f"Final Output JSON: {final_output_json_path}")
    logging.info(f"Final Output Summary: {final_output_summary_path}")

    if num_groups <= 0:
        logging.error("Number of groups must be positive.")
        console.print("[bold red]Error:[/bold red] Number of groups must be positive.")
        sys.exit(1)

    console.print("\n[bold blue]Processing CSV and balancing namespaces...[/bold blue]")

    try:
        # 1. Process CSV and calculate weights
        namespaces_data = process_input_csv(input_csv, weight_pvc, weight_core, weight_cr)

        if not namespaces_data:
            console.print(
                "[bold yellow]Warning:[/bold yellow] No valid namespace data found in the input CSV."
            )
            logging.warning("No valid namespace data found in the input CSV. Exiting.")
            sys.exit(0)

        # 2. Balance namespaces using greedy algorithm
        groups = balance_namespaces_greedy(namespaces_data, num_groups)

        # 3. Write JSON output
        write_json_output(groups, final_output_json_path)  # Use timestamped path

        # 4. Output summary (console and file)
        generate_and_write_summary(groups, final_output_summary_path, console)

    except ValueError as e:  # Catch specific error from process_input_csv
        # Ensure error is logged and printed
        console.print(f"[bold red]Error:[/bold red] {e}")
        logging.error(f"ValueError during processing: {e}")  # Add logging here
        sys.exit(1)
    except Exception as e:  # Catch other potential errors during processing
        console.print(f"[bold red]An unexpected error occurred during processing: {e}[/bold red]")
        logging.exception("An unexpected error occurred during processing.")
        sys.exit(1)

    console.print("\n[bold green]Balancing complete.[/bold green]")
    console.print(
        f"Detailed group assignments saved to: {final_output_json_path}"
    )  # Use timestamped path
    console.print(f"Summary saved to: {final_output_summary_path}")  # Use timestamped path
    logging.info("Schedule balancer finished.")


# --- Core Logic Functions --- #


def process_input_csv(
    input_csv_path: str, weight_pvc: float, weight_core: float, weight_cr: float
) -> List[Dict[str, Any]]:
    """Reads the input CSV, calculates weights, and returns processed data."""
    namespaces_data: List[Dict[str, Any]] = []
    logging.info(f"Reading and processing CSV: {input_csv_path}")
    try:
        with open(input_csv_path, mode="r", newline="", encoding="utf-8") as csvfile:
            reader = csv.DictReader(csvfile)
            if "Namespace" not in reader.fieldnames:
                logging.error(f"Input CSV '{input_csv_path}' missing required 'Namespace' column.")
                raise ValueError(
                    f"Input CSV '{input_csv_path}' missing required 'Namespace' column."
                )

            for row in reader:
                ns_name = row.get("Namespace", "")
                if not ns_name:
                    logging.warning("Skipping row with missing Namespace.")
                    continue

                # Helper to safely get and convert size fields
                def get_size(field_name: str) -> float:
                    val_str = row.get(field_name, "0")
                    try:
                        return float(val_str)
                    except (ValueError, TypeError):
                        logging.warning(
                            f"Invalid value '{val_str}' for {field_name} in namespace {ns_name}, using 0."
                        )
                        return 0.0

                pvc_gib = get_size("TotalPVCCapacityGiB")
                core_kib = get_size("TotalCoreResourcesSizeKiB")
                cr_kib = get_size("TotalCustomResourceSizeKiB")

                # Calculate weight
                weight = (pvc_gib * weight_pvc) + (core_kib * weight_core) + (cr_kib * weight_cr)

                namespaces_data.append(
                    {
                        "name": ns_name,
                        "weight": weight,
                        "pvc_gib": pvc_gib,
                        "core_kib": core_kib,
                        "cr_kib": cr_kib,
                    }
                )
    except FileNotFoundError:
        logging.error(f"Input CSV file not found: {input_csv_path}")
        raise
    except Exception:  # Remove unused 'e' variable
        logging.exception(f"Failed to read or process CSV file: {input_csv_path}")
        raise

    logging.info(f"Successfully processed {len(namespaces_data)} namespaces from CSV.")
    return namespaces_data


def balance_namespaces_greedy(
    namespaces_data: List[Dict[str, Any]], num_groups: int
) -> List[Dict[str, Any]]:
    """Distributes namespaces into groups using a greedy algorithm based on weight."""
    if not namespaces_data:
        return []

    # Sort namespaces by weight (descending)
    namespaces_data.sort(key=lambda x: x["weight"], reverse=True)
    logging.info("Sorted namespaces by calculated weight (descending).")

    # Initialize groups
    groups: List[Dict[str, Any]] = []
    for i in range(num_groups):
        groups.append(
            {
                "id": f"group_{i}",
                "namespaces": [],
                "namespace_count": 0,
                "total_calculated_weight": 0.0,
                "sum_pvc_gib": 0.0,
                "sum_core_kib": 0.0,
                "sum_cr_kib": 0.0,
            }
        )
    logging.info(f"Initialized {num_groups} empty groups.")

    # Apply greedy algorithm
    for ns_data in namespaces_data:
        # Find the group with the smallest current total weight
        target_group = min(groups, key=lambda g: g["total_calculated_weight"])

        # Assign namespace to the target group
        target_group["namespaces"].append(ns_data["name"])
        target_group["namespace_count"] += 1
        target_group["total_calculated_weight"] += ns_data["weight"]
        target_group["sum_pvc_gib"] += ns_data["pvc_gib"]
        target_group["sum_core_kib"] += ns_data["core_kib"]
        target_group["sum_cr_kib"] += ns_data["cr_kib"]

    logging.info("Finished assigning namespaces to groups.")
    return groups


def write_json_output(groups: List[Dict[str, Any]], output_json_path: str):
    """Writes the detailed group assignments to a JSON file."""
    json_output_data = {g["id"]: g for g in groups}
    logging.info(f"Preparing JSON output for {output_json_path}")
    try:
        json_dir = os.path.dirname(output_json_path)
        if json_dir:
            os.makedirs(json_dir, exist_ok=True)
        with open(output_json_path, "w", encoding="utf-8") as f:
            json.dump(json_output_data, f, indent=2)
        logging.info(f"Successfully wrote JSON output to {output_json_path}")
    except OSError as e:
        logging.error(f"Could not write JSON file '{output_json_path}': {e}")
        raise  # Re-raise to be caught by main
    except Exception:  # Remove unused 'e' variable
        logging.exception(f"Unexpected error writing JSON file: {output_json_path}")
        raise  # Re-raise to be caught by main


def generate_and_write_summary(
    groups: List[Dict[str, Any]], output_summary_path: str, console: Console
):
    """Generates summary, prints to console, and writes to text file."""
    logging.info(f"Generating summary for console and {output_summary_path}")
    if not groups:
        console.print("[bold yellow]Warning:[/bold yellow] No groups to summarize.")
        logging.warning("No group data available for summary.")
        return

    summary_table = Table(title="Namespace Group Balancing Summary")
    summary_table.add_column("Group ID", style="cyan", no_wrap=True)
    summary_table.add_column("Namespaces", style="magenta", justify="right")
    summary_table.add_column("Total Weight", style="green", justify="right")
    summary_table.add_column("Sum PVC (GiB)", style="yellow", justify="right")
    summary_table.add_column("Sum Core (KiB)", style="blue", justify="right")
    summary_table.add_column("Sum CR (KiB)", style="red", justify="right")

    summary_lines = []  # For text file
    header = f"{'Group ID':<12} {'Namespaces':>12} {'Total Weight':>18} {'Sum PVC (GiB)':>18} {'Sum Core (KiB)':>18} {'Sum CR (KiB)':>18}"
    summary_lines.append(header)
    summary_lines.append("-" * len(header))

    for group in groups:
        weight_str = f"{group['total_calculated_weight']:.2f}"
        pvc_str = f"{group['sum_pvc_gib']:.2f}"
        core_str = f"{group['sum_core_kib']:.2f}"
        cr_str = f"{group['sum_cr_kib']:.2f}"
        summary_table.add_row(
            group["id"], str(group["namespace_count"]), weight_str, pvc_str, core_str, cr_str
        )
        line = f"{group['id']:<12} {group['namespace_count']:>12} {weight_str:>18} {pvc_str:>18} {core_str:>18} {cr_str:>18}"
        summary_lines.append(line)

    # Print summary table to console
    console.print("\n")  # Spacer before table
    console.print(summary_table)

    # Write summary to text file
    try:
        summary_dir = os.path.dirname(output_summary_path)
        if summary_dir:
            os.makedirs(summary_dir, exist_ok=True)
        with open(output_summary_path, "w", encoding="utf-8") as f:
            f.write("Namespace Group Balancing Summary\n")
            f.write("=" * len(header) + "\n")
            for line in summary_lines:
                f.write(line + "\n")
        logging.info(f"Successfully wrote summary to {output_summary_path}")
    except OSError as e:
        logging.error(f"Could not write summary file '{output_summary_path}': {e}")
        # Don't exit, just log the error and notify user
        console.print(
            f"[bold red]Error:[/bold red] Could not write summary file '{output_summary_path}': {e}"
        )
    except Exception:  # Remove unused 'e' variable
        logging.exception(f"Unexpected error writing summary file: {output_summary_path}")
        # Print generic error to console, details are in the log
        console.print(
            "[bold red]Error:[/bold red] Unexpected error writing summary file. See log for details."
        )


if __name__ == "__main__":
    main()
